FROM public.ecr.aws/lambda/python:3.10
COPY . .
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.server.handler" ]